# Generated by Django 5.2.12 on 2026-05-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreview',
            name='completed_minutes_by_category',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dailyreview',
            name='planned_minutes_by_category',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dailyreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
