# Generated by Django 5.2.12 on 2026-08-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mgr', '0003_user_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('strategic', 'Strategic'), ('light_premium', 'Light Premium'), ('dark_4a', 'Dark 4a')], default='classic', max_length=32),
        ),
    ]
