# Generated by Django 5.2.12 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_mgr", "0004_alter_userpreferences_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="chat_suggestions",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
