# Generated by Django 5.2.12 on 2026-09-02

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("templates_mgr", "0005_userpreferences_chat_suggestions")]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="focus_indicator_opacity",
            field=models.FloatField(
                default=0.7,
                validators=[MinValueValidator(0.2), MaxValueValidator(1.0)],
            ),
        ),
    ]
