# Generated by Django 5.2.12 on 2026-04-06 10:26

import django.db.models.deletion
import schedules.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('reviewed', 'Reviewed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.TimeField(validators=[schedules.validators.validate_five_minute_granularity])),
                ('end_time', models.TimeField(validators=[schedules.validators.validate_five_minute_granularity])),
                ('category', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='schedules.schedule')),
            ],
            options={
                'ordering': ['start_time', 'sort_order'],
            },
        ),
    ]
