# Generated by Django 5.2.12 on 2026-04-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timeblock',
            index=models.Index(fields=['schedule', 'start_time', 'end_time'], name='schedules_t_schedul_8d6c7c_idx'),
        ),
    ]
