# Generated by Django 5.2.12 on 2026-04-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_timeblock_schedules_t_schedul_8d6c7c_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='timeblock',
            name='schedules_t_schedul_8d6c7c_idx',
        ),
        migrations.AddIndex(
            model_name='timeblock',
            index=models.Index(fields=['schedule', 'start_time', 'end_time', 'sort_order'], name='schedules_t_schedul_b03c0e_idx'),
        ),
    ]
