# Generated by Django 5.2.12 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("schedules", "0006_category_alter_timeblock_category")]

    operations = [
        migrations.AddField(
            model_name="userschedulesettings",
            name="time_zone",
            field=models.CharField(default="UTC", max_length=64),
        ),
    ]
