# Generated by Django 5.2.12 on 2026-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_sync', '0002_travelrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrule',
            name='calendar_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='travelrule',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
