# Generated by Django 5.2.12 on 2026-04-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('schedules', '0004_remove_timeblock_schedules_t_schedul_8d6c7c_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aiinteraction',
            index=models.Index(fields=['schedule', '-created_at'], name='ai_interact_sched_created_idx'),
        ),
    ]
