# Generated by Django 5.2.12 on 2026-04-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiinteraction_ai_interact_sched_created_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
