# Generated by Django 5.2.12 on 2026-08-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aiinteraction_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinteraction',
            name='kind',
            field=models.CharField(choices=[('command', 'Command'), ('draft', 'Draft'), ('chat', 'Chat')], default='chat', max_length=10),
        ),
    ]
